name: BT Org Build and Test

on:
    workflow_call:
        inputs:
            build-target-path:
                required: true
                type: string
        secrets:
            nuget-source-access-token:
                required: true
            nuget-source-url:
                required: true
    pull_request:
        branches: [$default-branch, dev, test]

jobs:
    build_and_test:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2
              with:
                fetch-depth: 0

            - name: Setup .NET
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: 6.0.x
                  source-url: ${{ secrets.nuget-source-url }}
              env:
                  NUGET_AUTH_TOKEN: ${{ secrets.nuget-source-access-token }}

            - name: Restore dependencies
              run: dotnet restore ${{ inputs.build-target-path }}

            - name: Build
              run: dotnet build --no-restore ${{ inputs.build-target-path }}

            - name: Test
              run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage ${{ inputs.build-target-path }} 
              
            - name: PR Metrics
              uses: microsoft/PR-Metrics@v1.5.7
              env:
                  PR_METRICS_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  continue-on-error: false
                  base-size: 200
                  growth-rate: 2.0
                  test-factor: 1.0
    calculate_code_coverage:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            
            - name: Setup .NET
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: 6.0.x
                  source-url: ${{ secrets.nuget-source-url }}
              env:
                  NUGET_AUTH_TOKEN: ${{ secrets.nuget-source-access-token }}
            - name: Test
              run: dotnet test --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage ${{ inputs.build-target-path }} 
      
            # - name: Code Coverage Report
            #   uses: irongut/CodeCoverageSummary@v1.3.0
            #   with:
            #     filename: coverage/**/coverage.cobertura.xml
            #     badge: true
            #     fail_below_min: true
            #     format: markdown
            #     hide_branch_rate: false
            #     hide_complexity: true
            #     indicators: true
            #     output: both
            #     thresholds: '60 80'

            # - name: Produce the coverage report
            #   uses: insightsengineering/coverage-action@v2
            #   with:
            #     path: coverage/**/coverage.cobertura.xml
            #     threshold: 80
            #     fail: true
            #     publish: true
            #     diff: true
            #     diff-branch: ${{ github.base_ref }}
            #     diff-storage: _xml_coverage_reports

            - name: Publish coverage report for changed files
              uses: 5monkeys/cobertura-action@v8
              with:
                repo_token: ${{ secrets.GITHUB_TOKEN }}
                path: coverage/**/coverage.cobertura.xml
                skip_covered: false
                minimum_coverage: 80
                show_line: true
                show_missing: true
                only_changed_files: true
                report_name: Changed files code coverage
              continue-on-error: false

            # - name: Add Coverage PR Comment
            #   uses: marocchino/sticky-pull-request-comment@v2
            #   if: github.event_name == 'pull_request'
            #   with:
            #     recreate: true
            #     path: code-coverage-results.md
            